version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  api1:
    build: .
    env_file:
      - .env
    ports:
      - "3001:3000"
    depends_on:
      - elasticsearch

  api2:
    build: .
    env_file:
      - .env
    ports:
      - "3002:3000"
    depends_on:
      - elasticsearch

  api3:
    build: .
    env_file:
      - .env
    ports:
      - "3003:3000"
    depends_on:
      - elasticsearch

  load_balancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    depends_on:
      - api1
      - api2
      - api3
